<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TempFolioDetails extends Model
{
    use HasFactory;
    protected $table="tt_folio_details";
    protected $fillable = [
        'rnt_id',
        'product_code',
        'amc_code',
        'folio_no',
        'folio_date',
        'dividend_option',
        'first_client_name',
        'joint_name_1',
        'joint_name_2',
        'add_1',
        'add_2',
        'add_3',
        'city',
        'pincode',
        'state',
        'country',
        'tpin',
        'f_name',
        'dob',
        'm_name',
        'phone_residence',
        'phone_res_1',
        'phone_res_2',
        'phone_ofc',
        'phone_ofc_1',
        'phone_ofc_2',
        'fax_residence',
        'fax_ofc',
        'tax_status',
        'occ_code',
        'email',
        'bank_acc_no',
        'bank_name',
        'bank_ifsc',
        'acc_type',
        'branch',
        'bank_add_1',
        'bank_add_2',
        'bank_add_3',
        'bank_city',
        'bank_phone',
        'bank_state',
        'bank_country',
        'invs_id',
        'arn_no',
        'pan',
        'pan_2_holder',
        'pan_3_holder',
        'mobile',
        'report_date',
        'report_time',
        'occupation_des',
        'mode_of_holding',
        'mode_of_holding_des',
        'mapin_id',
        'aadhaar_1_holder',
        'aadhaar_2_holder',
        'aadhaar_3_holder',
        'guardian_name',
        'guardian_aadhaar',
        'guardian_pan',
        'guardian_relation',
        'reinvest_flag',
        'nom_optout_status',
        'nom_name_1',
        'nom_relation_1',
        'nom_per_1',
        'nom_name_2',
        'nom_relation_2',
        'nom_per_2',
        'nom_name_3',
        'nom_relation_3',
        'nom_per_3',
        'amc_flag',
        'scheme_flag',
        'delete_flag',
        'deleted_date',
        'deleted_by',
    ];
}
